# Generated by Django 3.0.8 on 2020-07-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_thumbnail', models.CharField(max_length=256)),
                ('thumbnail', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('published_date', models.CharField(max_length=10)),
                ('page_count', models.IntegerField(blank=True)),
                ('language', models.CharField(max_length=128)),
                ('authors', models.ManyToManyField(to='bookbrowser.Author')),
                ('image_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookbrowser.ImageLink')),
                ('industry_identifiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookbrowser.IndustryIdentifier')),
            ],
        ),
    ]
